name: Convert and Sync Colab Notebooks

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual triggering from GitHub's Actions tab

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Jupytext and Dependencies
        run: |
          pip install jupytext jupyter_client ipykernel
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Convert percent-scripts to ipynb
        run: |
          jupytext --to ipynb --set-kernel python3 docs/source/tutorials/*.py

      - name: Convert Sphinx roles to Read the Docs links
        run: python tools/rtd_links.py docs/source/tutorials/*.ipynb

      - name: Deploy converted notebooks to colab-notebooks branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/source/tutorials
          destination_dir: .
          publish_branch: colab-notebooks
          exclude_assets: '*.py'
